/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 box.gltf --transform
Author: Agustín Hönnun (https://sketchfab.com/Agustin_Honnun)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cardboard-box-free-agustin-honnun-ace6b94bb4ac4b03ad488411ae123e01
Title: Cardboard Box [FREE] | Agustin Honnun
*/

// import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/box-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} scale={38.55} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/box-transformed.glb')
